name: trolley
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  adaptive_platform_ui: ^1.0.1
  app_links: ^7.2.1
  cupertino_icons: ^2.0.0
  drift: ^2.35.0
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  share_plus: ^13.3.0
  supabase_flutter: ^2.18.0
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.35.0
  build_runner: ^2.16.1

flutter:
  uses-material-design: true
